pub mod flappy_bird;
pub mod pacman_eat;
// pub mod platformer;
pub mod novel;
pub mod properties;
pub mod prelude;
pub mod tilemap;
pub mod core;
pub mod shaders;
pub mod global_music;
pub mod hints;
pub mod fake_end;
pub mod geometry_dash;
pub mod pathfinder;
pub mod miami;